# server setup
server:
    port: 8001

# Jasypt Key
jasypt:
    encryptor:
        password: MasterKey

application:
    security:
        jwt:
            secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
            expiration: 86400000
            refresh-token:
                expiration: 1209600000

spring:
    application:
        name: mail-exchange
    # DB Setup
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mail-flock
        username: root
        password: ENC(qixg6OXUBW57lOOIKn8GU6ZjyxVYwHy1)
    # Mail Config
    mail:
        host: ENC(+T4OYuJmPcVkCz4PPIjmoQVmMFLMrgmm)
        port: 587
        username: ENC(aNTvTW0Lrm26Bklx/ZV0f3nwOy8aVna/WEY9pZTvbhU=)
        password: ENC(B2P0u8NyjmYR4Oyj5u1MTdjAHX6zvhJgZ5q0iQNFc08=)
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: create-drop
